### ISSUE TITLE
Package.json quebrado

### ISSUE THREAD

**Issue by thebergamo** [IAMFELIPESOUZA/landing-nodeconf-br#6]
Quando clonei o repositório e tentei rodar o mesmo com os comandos no README.md não consegui rodar nenhum comando. Olhando no package.json verifiquei que não existe nenhum dos comandos elencados.
Como não manjo muito de sytlus e gulp então não sei rodar :disappointed_relieved:

**Comment by gpedro** [comment]
@thebergamo teste novamente.
